steps:
  # Build the application
  - name: 'gcr.io/cloud-builders/dotnet'
    args: ['publish', '-c', 'Release', '-o', 'publish']
    dir: 'ChessDecoderApi'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'gcr.io/$PROJECT_ID/chess-decoder-api:$COMMIT_SHA', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chess-decoder-api:$COMMIT_SHA']

  # Create Cloud Storage buckets first
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Create Cloud Storage buckets if they don't exist
        DATABASE_BUCKET="chessdecoder-db-$$PROJECT_ID"
        IMAGES_BUCKET="chessdecoder-images-$$PROJECT_ID"
        
        echo "Creating Cloud Storage buckets..."
        
        # Create database bucket
        if ! gsutil ls -b gs://$$DATABASE_BUCKET 2>/dev/null; then
          echo "Creating database bucket: $$DATABASE_BUCKET"
          gsutil mb -p $$PROJECT_ID -c STANDARD -l us-central1 gs://$$DATABASE_BUCKET
        else
          echo "Database bucket already exists: $$DATABASE_BUCKET"
        fi
        
        # Create images bucket
        if ! gsutil ls -b gs://$$IMAGES_BUCKET 2>/dev/null; then
          echo "Creating images bucket: $$IMAGES_BUCKET"
          gsutil mb -p $$PROJECT_ID -c STANDARD -l us-central1 gs://$$IMAGES_BUCKET
          # Make images bucket public for serving images
          gsutil iam ch allUsers:objectViewer gs://$$IMAGES_BUCKET
        else
          echo "Images bucket already exists: $$IMAGES_BUCKET"
        fi

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chess-decoder-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chess-decoder-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'ASPNETCORE_ENVIRONMENT=Production,ConnectionStrings__DefaultConnection=Data Source=/app/data/chessdecoder.db,PORT=8080,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_DATABASE_BUCKET=chessdecoder-db-$PROJECT_ID,GOOGLE_CLOUD_IMAGES_BUCKET=chessdecoder-images-$PROJECT_ID'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,GOOGLE_VISION_API_KEY=google-vision-api-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest'

  # Grant Cloud Run service account permissions for Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Get the default compute service account
        SERVICE_ACCOUNT=$$(gcloud run services describe chess-decoder-api --region=us-central1 --format="value(spec.template.spec.serviceAccountName)" 2>/dev/null || echo "")
        if [ -z "$$SERVICE_ACCOUNT" ]; then
          SERVICE_ACCOUNT=$$PROJECT_ID-compute@developer.gserviceaccount.com
        fi
        
        echo "Granting Cloud Storage permissions to service account: $$SERVICE_ACCOUNT"
        
        # Grant Storage Object Admin role for database bucket
        gcloud projects add-iam-policy-binding $$PROJECT_ID \
          --member="serviceAccount:$$SERVICE_ACCOUNT" \
          --role="roles/storage.objectAdmin"
        
        # Grant Storage Object Viewer role for images bucket
        gcloud projects add-iam-policy-binding $$PROJECT_ID \
          --member="serviceAccount:$$SERVICE_ACCOUNT" \
          --role="roles/storage.objectViewer"

images:
  - 'gcr.io/$PROJECT_ID/chess-decoder-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
