services:
  # Redis for caching (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: chess-decoder-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chess-decoder-network

volumes:
  redis_data:
    driver: local

networks:
  chess-decoder-network:
    driver: bridge
